apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-gitops
  name: test-gitops
  namespace: test-gitops-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-gitops
  strategy: {}
  template:
    metadata:
      labels:
        app: test-gitops
    spec:
      containers:
        - image: httpd
          name: httpd
---
apiVersion: v1
kind: Service
metadata:
  name: test-gitops-svc
  namespace: test-gitops-ns
spec:
  type: LoadBalancer
  selector:
    app: test-gitops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
